version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app      # Mount source for development
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:80"           # Expose nginx port
    depends_on:
      - backend
    volumes:
      - ./frontend:/app     # Optional: for development, live edits won't auto-reload with nginx
